### PR TITLE
add octave plugin's .m files to octave's load path

### LINKED ISSUE #7: Octave plugin error of undefined tmrepl in tm-start.m
I've met an error of "tmrepl undefined in tm-start.m" when using octave session in TeXmacs. It was solved by adding "$TEXMACS_PATH/plugins/octave/octave/tm" to octave's load path. Then octave works well in TeXmacs so far.

Some related information:

OS: Arch Linux
TeXmacs version: 1.99.8
Octave version: 5.1.0

Hope it helps.

### PR DESCRIPTION
**Pull request by chen-chao**
fix #7 .

### CODE REVIEW

**Comment by chen-chao** [comment]
OK, I've found the [.octaverc](https://github.com/texmacs/plugins/blob/master/octave/octave/.octaverc) file in the project which fixes the issue, but not contained in my installed TeXmacs. Maybe this is a packaging problem.

**Comment by da-liii** [comment]
@chen-chao  Thanks for your pull request.

You may package GNU TeXmacs by yourself. 

## Ref
+ https://github.com/texmacs/texmacs/wiki
+ https://github.com/texmacs/texmacs/blob/master/cmake/build_deb.sh

**Comment by da-liii** [comment]
It seems the plot functionality for octave does not work. Any clues to fix it?

**Comment by chen-chao** [comment]
I'll look at it if I have time.

Darcy Shen <notifications@github.com> 于 2019年4月21日周日 16:55写道：

**Comment by chen-chao** [comment]
I've found a method from [contour.m](https://github.com/texmacs/plugins/blob/master/octave/octave/plot/contour.m) to solve the problem. It saves the figure to a temp file and then writes to stdout(TeXmacs should be able to read it, I don't quite know this part). Former scripts are broken because octave throws many obsolete functions away. But the color seems not right now, which may needs to be fixed later.

**Comment by da-liii** [comment]
@chen-chao  The octave plugin has been refactored. I've fixed the plotting problem. Welcome to help improving the Octave plugin

https://github.com/texmacs/octave

**Pull request closed without merging**
